kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-external-dns-webhook
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
