name: Package and push Helm chart

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/helm.yml'
      - 'deploy/chart/**'

jobs:
  push-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Push chart
      uses: appany/helm-oci-chart-releaser@v0.3.0
      with:
        name: helm-external-dns-hostsfile-webhook
        repository: joscha-alisch
        tag: 0.2.0
        path: deploy/chart
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
